import { Inter } from "next/font/google";
import localFont from "next/font/local";
import SmoothScroller from "@/components/SmoothScroller";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const porsche = localFont({
  src: "../public/porsche.ttf",
  display: "swap",
  variable: "--font-porsche"
})

export const metadata = {
  title: "Porsche 911",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${porsche.variable}`}>
        <SmoothScroller>
          {children}
        </SmoothScroller>
      </body>
    </html>
  );
}
